title: 日向坂46 Googleカレンダー
description: 日向坂46のスケジュールを自身のGoogleカレンダーへ追加できるようにすることで、推し活ライフのサポートを目指しています。 
lang: ja_JP
plugins:
  - jekyll-seo-tag
url: https://github.com/CircleTenThanks/Hinatazaka46Calendar
social:
  name:  CircleTenThanks 
  links:
    - https://github.com/CircleTenThanks
    - https://www.youtube.com/@CircleTenThanks
    - https://twitter.com/CircleTenThanks