layout: default
title: 日向坂46 Googleカレンダー
description: 日向坂46のスケジュールをGoogleカレンダーへ自動追加し、充実したおひさまライフをサポートします。
lang: ja_JP
plugins:
  - jekyll-seo-tag
url: https://github.com/CircleTenThanks
twitter:
  username: CircleTenThanks
  card: summary_large_image
social:
  name:  CircleTenThanks 
  links:
    - https://github.com/CircleTenThanks
    - https://www.youtube.com/@CircleTenThanks
    - https://twitter.com/CircleTenThanks
defaults:
  - scope:
      path: ""
    values:
        image: /img/overture.jpg